Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .api_urls import urlpatterns as api_urls 
#from django.conf import settings
#from django.conf.urls.static import static  #para los statics



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('modules.Home.urls')),
    url(r'^home/', include('modules.Home.urls', namespace='Home', app_name='Home')),    
    url(r'^publicaciones/', include('modules.Publicaciones.urls', namespace='Publicaciones', app_name='Publicaciones')),    
    url(r'^api/v1/', include(api_urls)), # url de API
]
#+ static(settings.MEDIA_URL,settings.MEDIA_ROOT) #clase que concatena rutas 2
#+ static(setting.STATIC_URL,settings.STATIC_ROOT)  # clase quedirecciona todo lo que encuentra /static/ a la ruta 

modules/Home/urls.py
from django.conf.urls import url, include
from .views import index, contactos, login, singup, Logout


urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^contactos/$', contactos, name='contactos'),
    url(r'^login/$', login, name= 'login'),
    url(r'^signup/$', singup, name='signup'),
    url(r'^logout/$', Logout, name='logout'),
]	

modules/Publicaciones/urls.py
from django.conf.urls import url
from .views  import index, add

urlpatterns = [
    url(r'^$', index, name='index-publicacion'),
    url(r'^add/$', add, name='add-publicacion'),
]

modules/Publicaciones/models.py
from django.db import models
from django.contrib.auth.models import User # modelo generico de django

TAGS = (
	('TC', 'Tecnología'),
	('CT', 'Científico'),
	('PR', 'Programación')
)

# Manager
#class carlossgPublicacionesManager(models.Manager):

	#def get_queryset(self):
	#	return super(carlossgPublicacionesManager,self).get_queryset().filter(autor__usermame='carlossg')

class Publicacion (models.Model):
	id = models.AutoField(primary_key=True)
	nombre = models.CharField(max_length=50)
	contenido = models.TextField()
	fecha = models.DateField(auto_now_add=True)
	autor = models.ForeignKey(User, on_delete=models.CASCADE, related_name="publicaciones")  #related_name es el nombre de la relacion
	tags = models.CharField(choices=TAGS, max_length=50) # opciones de eleccción
	imagen = models.ImageField(upload_to='Publicaciones/', null=True, blank=True) # para el admin, null puede o no haber vacio, blank pone todos blancos

	# Manager
	#carlossg_publicacion = carlossgPublicacionesManager()

	#da nombre al objeto	
	def __str__(self):
		return "%s %s" % ("Publicacion: " , self.nombre)

modules/Home/forms.py
from django.forms import ModelForm 
from django.contrib.auth.models import User 


class LoginForm(ModelForm):

	class Meta: 
		model = User
		fields = ['username', 'password']

modules/Home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from .forms import LoginForm
from django.contrib.auth import authenticate, login as log, logout


def index(request):
	user = request.user

	return render(request, 'Home/index.html',{"user":user})

def contactos(request):

	return HttpResponse('<b>Pagina de Contactos</b>')

def singup(request):
		if request.method == 'POST':
			firts_name = request.POST['firts_name']
			last_name = request.POST['last_name']
			username = request.POST['username']
			password = request.POST['password']

			user = User.objects.get(username=username)
			if user is None:

				user = User.objects.create_user(
					first_name = first_name,
					last_name = last_name,
					username = username,
					password = password
				)
				user.save()

				return HttpResponse('<b>Usuario Registrado</b>')

			else:

				return HttpResponse('<b>Usuario ya Existe</b>')	
			
		else:

			return render(request, "Home/signup.html")		

def login(request):
		
		if request.method == 'POST':
			
			user = authenticate(username=request.POST['username'],
			password=request.POST['password'])

			if user is not None:
				log(request, user)
				return redirect('Home:index')

			else:

				return HttpResponse("Error en usuario o contraseña")

		else:

			return render(request, 'Home/login.html')

def Logout(request):
	logout(request)
	return redirect('Home:index')

modules/Publicaciones/views.py
from django.shortcuts import render, redirect
from  .models import TAGS, Publicacion
from .functions import hadle_upload_file


def index(request):

	public = [
		{	"nombre":"Mi primer Proyecto en Django",
			"autor":"Alberto Durand",
			"fecha":"07-02-2017",
			"raiting":5
		},

		{	"nombre":"Mi segundo Proyecto en Django",
			"autor":"Jose Carlos Sandoval",
			"fecha":"01-02-2017",
			"raiting":3
		},

		{	"nombre":"Mi tercer Proyecto en Django",
			"autor":"Javier Fernandez",
			"fecha":"01-01-2017",
			"raiting":2
		}
	]
	

	return render(request, 'Publicaciones/index.html', {"publicaciones":public})  # (2) Template html, (3) contexto en diccionari, para pasar más de una variable

def add(request):

	if request.method == 'POST':
		types = {'image/jpeg':'.jpg', 'image/png':'.png', 'image/gif': '.gif'}  #simula un switch en python
		image_name = request.FILES['imagen'].name + types[request.FILES['imagen'].content_type]
		if request.user.is_authenticated():
			publicacion = Publicacion()
			publicacion.nombre = request.POST['nombre']
			publicacion.contenido = request.POST['contenido']	
			publicacion.tags = request.POST['tag']
			publicacion.autor = request.user
			publicacion.imagen = hadle_upload_file(request.FILES['imagen'], image_name) # iamge_name = nombre del archivo

			publicacion.save()

			return redirect('Publicaciones:index-publicacion')


	else:
		dict_tags = dict((x,y) for x,y in TAGS)
		return render(request, 'Publicaciones/add.html', { "tags":dict_tags})	

templates/Home/index.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}Home{% endblock %}
{% block 'content' %}
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>
{% endblock %}

templates/Home/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block content %}
<div class="row">
<form class="col s12" action= "{% url 'Home:login' %}" method="post">
 {% csrf_token %}

 <div class="row">
  <div class="input-field col s12">
    <input id="username" type="text" class="validate" name="username">
    <label for="username">Username</label>
  </div>
</div>
<div class="row">
  <div class="input-field col s12">
    <input id="password" type="password" class="validate" name="password">
    <label for="password">Password</label>
  </div>
</div>
 <input type="submit" name="enviar" value="Enviar">
 
</form>
</div>
{% endblock content %}

templates/Home/signup.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Signup{% endblock title %}
{% block content %}
<div class="row">
<form class="col s12" action="{% url 'Home:signup' %}" method="post">
{% csrf_token %}
 <div class="row">
   <div class="input-field col s6">
     <input  id="first_name" type="text" class="validate" name="firts_name">
     <label for="first_name">First Name</label>
   </div>
   <div class="input-field col s6">
     <input id="last_name" type="text" class="validate" name="last_name">
     <label for="last_name">Last Name</label>
   </div>
 </div>
 <div class="row">
   <div class="input-field col s12">
     <input id="username" type="text" class="validate" name="username">
     <label for="username">Username</label>
   </div>
 </div>
 <div class="row">
   <div class="input-field col s12">
     <input id="password" type="password" class="validate" name="password">
     <label for="password">Password</label>
   </div>
 </div>
 <div class="row">
   <div class="input-field col s12">
     <input id="email" type="email" class="validate" name="email">
     <label for="email">Email</label>
   </div>

 </div>
 <input type="submit" name="enviar" value="enviar">
</form>
</div>
{% endblock content %}

templates/Publicaciones/add.html
{% extends 'base.html'%}
{% block 'title' %}Publicaciones|add{%endblock%}
{% block 'content'%}
	<form class="" action="{%  url 'Publicaciones:add-publicacion' %}" method="post" enctype="multipart/form-data">
  {% csrf_token %}
      <div class="row">
        <div class="input-field col s6">
          <input  id="Nombre" type="text" name="nombre" class="validate">
          <label for="first_name">Nombre</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <textarea   type="text" name="contenido" class="validate"></textarea>
          <label for="first_name">Contenido</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <select class="" name="tag">
            <option value="" selected>--Seleciona opcion---</option>
          {%for key, values in tags%}
            <option value="{{key}}">{{value}}</option>
          {%endfor%}  
          </select>
          <label for="first_name">TAGS</label>
        </div>
      </div>
      <div class="row">
        <div class="input-field col s6">
          <input name="imagen" id="" type="file" class="validate">
          <label for="first_name">Imagen</label>
        </div>
      </div>
      <button class="btn waves-effect waves-light" type="submit" name="action">Submit
        <i class="material-icons right">send</i>
      </button>
    </div>	  
	</form>
{%endblock%}

templates/Publicaciones/index.html
{% extends 'base.html' %}
{% load static %}
{% block 'title' %}Publicaciones{% endblock %}
{% block 'content' %}
	{% comment %}
	{{ publicaciones.nombre | upper }} <!-- variables  del contexto aplicando filter para upper -->
	</br>	
	{{ publicaciones.nombre | length }}
	</br>
	{{ publicaciones.edad | default:"No tiene" }}
	</br>
	{{ publicaciones.fecha | date:"D d M Y" }}
	{% endcomment %}

	{% for publicacion in publicaciones %}
		{% for key, value in publicacion.items %}
			{% if key == "raiting" and value <= 3 %}
				<h3>Menos Destacados</h3>
				{{ key }} : {{ value }}
			{% endif %}
			{{ key }} : {{ value }}	
			<br>			
		{% endfor %}
		<br>
		<hr>		
	{% endfor %}
	<a href="{% url 'Publicaciones:add-publicacion %'}">Crear publicacion</a>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>{% block 'title' %} {% endblock %}</title>
	<link rel="stylesheet" href="{% static 'css/materialize.css' %}" />
</head>
<body>
	<nav>
    	<div class="nav-wrapper">
      		<a href="#" class="brand-logo right">Logo Blog backend</a>
          {% if user.is_authenticated %}
            <span style="margin-left:50%;">Hola: {{user.username}}</span>
            <a href="#">Mi perfil</a>
            <a href="{% url 'Publicaciones:index-publicacion' %}">Mis publicaciones</a>
            <a href="{% url 'Home:logout' %}">Logout</a>


          {% else %}

      		  <ul id="nav-mobile" class="left hide-on-med-and-down">
        		<li><a href="{% url 'Home:signup' %}">Sign up</a></li>
        		<li><a href="{% url 'Home:login' %}">Login</a></li>
      		</ul>
          {% endif %}
    	</div>
  	</nav>
	{% block 'content' %}
	{% endblock %}
	<script src="{% static 'js/jquery-3.1.1.min.js' %}" />
  <script src="{% static 'js/materialize.min.js' %}" />
  <script src="{% static 'js/app.js' %}" />
  
</body>
</html>	